package chatapp;

import com.sun.org.apache.xalan.internal.lib.ExsltDatetime;
import java.io.*;
import java.net.*;


public class client extends javax.swing.JFrame {

    ObjectOutputStream outputSTM;
    ObjectInputStream inputSTM;
    
    public client() throws IOException {
        
        initComponents();
        Socket connectionSocket = new Socket("localhost",5000);
        outputSTM = new ObjectOutputStream(connectionSocket.getOutputStream());
        inputSTM = new ObjectInputStream(connectionSocket.getInputStream());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setBackground(new java.awt.Color(78, 152, 87));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 190, 30));

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      checkSpace();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkSpace(){
        
          if (!jTextField1.getText().equals("")) {
            String msg = jTextField1.getText();
            SendMessage(msg);
            chatSave(msg);
            jTextField1.setText("");
        }
          
    }
    
    private void chatSave(String msg){
        
        try{
            FileOutputStream outFile = new FileOutputStream("chat.txt", true);
            PrintWriter write = new PrintWriter(outFile);
            write.println("client :"+msg+" ");
            write.close();
        }catch(Exception e){
            System.out.println(e.toString());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        
        client c = new client();
        c.setVisible(true);
        c.ReciveMessage();
     
    }
    
    private void SendMessage(String msg) {
        
        String time = ExsltDatetime.time();
        time = time.substring(0, 5);
        try {
            outputSTM.writeObject(msg);
            jTextArea1.append("\t\t"+ " " + msg + " " + time + "\n");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }

    private void ReciveMessage() {
        
        String msg;
        String time = ExsltDatetime.time();
        time = time.substring(0, 5);
        while (true) {
            try {
                msg = (String) inputSTM.readObject();
                jTextArea1.append("  " + msg + " " + time + "\n");
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
 
}
